CREATE TABLE user_email (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(40), last_name VARCHAR(40), email VARCHAR(40));

CREATE TABLE email_alias (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, primary_email VARCHAR(40), alias VARCHAR(40));
